### ISSUE TITLE
Ability to skip license headers?

### ISSUE THREAD

**Issue by nevillelyh** [criteo/socco#2]
A lot of our examples have Apache license headers. `@hide` doesn't seem to work on those. Is there a way to skip them?

**Comment by guillaumebort** [comment]
I don't think it is possible for now. Can you please open a pull request with an exemple source including this comment?

**Comment by nevillelyh** [comment]
PR #3

**Comment by guillaumebort** [comment]
Thanks, __0.1.9__ is being released with the fix.
